#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: 94c6be0
#
Name     : R-reformulas
Version  : 0.4.0
Release  : 1
URL      : https://ftp.osuosl.org/pub/cran//src/contrib/reformulas_0.4.0.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran//src/contrib/reformulas_0.4.0.tar.gz
Summary  : Machinery for Processing Random Effect Formulas
Group    : Development/Tools
License  : GPL-3.0
Requires: R-Rdpack
BuildRequires : R-Rdpack
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
## reformulas
<!-- badges: start -->
[![R-CMD-check](https://github.com/bbolker/reformulas/actions/workflows/R-CMD-check.yaml/badge.svg)](https://github.com/bbolker/reformulas/actions/workflows/R-CMD-check.yaml)
<!-- badges: end -->

%prep
%setup -q -n reformulas

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1738186088

%install
export SOURCE_DATE_EPOCH=1738186088
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/reformulas/DESCRIPTION
/usr/lib64/R/library/reformulas/INDEX
/usr/lib64/R/library/reformulas/Meta/Rd.rds
/usr/lib64/R/library/reformulas/Meta/features.rds
/usr/lib64/R/library/reformulas/Meta/hsearch.rds
/usr/lib64/R/library/reformulas/Meta/links.rds
/usr/lib64/R/library/reformulas/Meta/nsInfo.rds
/usr/lib64/R/library/reformulas/Meta/package.rds
/usr/lib64/R/library/reformulas/NAMESPACE
/usr/lib64/R/library/reformulas/NEWS.md
/usr/lib64/R/library/reformulas/R/reformulas
/usr/lib64/R/library/reformulas/R/reformulas.rdb
/usr/lib64/R/library/reformulas/R/reformulas.rdx
/usr/lib64/R/library/reformulas/REFERENCES.bib
/usr/lib64/R/library/reformulas/help/AnIndex
/usr/lib64/R/library/reformulas/help/aliases.rds
/usr/lib64/R/library/reformulas/help/paths.rds
/usr/lib64/R/library/reformulas/help/reformulas.rdb
/usr/lib64/R/library/reformulas/help/reformulas.rdx
/usr/lib64/R/library/reformulas/html/00Index.html
/usr/lib64/R/library/reformulas/html/R.css
/usr/lib64/R/library/reformulas/tests/tinytest.R
/usr/lib64/R/library/reformulas/tinytest/test_anySpecial.R
/usr/lib64/R/library/reformulas/tinytest/test_doubleVertNotation.R
/usr/lib64/R/library/reformulas/tinytest/test_noSpecial.R
/usr/lib64/R/library/reformulas/tinytest/test_nobar.R
/usr/lib64/R/library/reformulas/tinytest/test_utils.R
